language: python
sudo: required
python:
  - "2.7"
addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - gfortran
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - python setup.py sdist
  - python setup.py install
script:
  - pip install transforms3d sympy
  - python -m unittest discover -s fluxer
  - python setup.py egg_info
